# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@deno/shim-deno-0.5.0" = {
      name = "_at_deno_slash_shim-deno";
      packageName = "@deno/shim-deno";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@deno/shim-deno/-/shim-deno-0.5.0.tgz";
        sha512 = "bx2TT/WwmpRlnk2Q0qe9xJMzbyKyl7Uyz9cdXEn756Obu15bRanLiVa/3+09Bg8HYL+mUXydWzh32/oxsVv6dw==";
      };
    };
    "@deno/shim-deno-test-0.3.3" = {
      name = "_at_deno_slash_shim-deno-test";
      packageName = "@deno/shim-deno-test";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@deno/shim-deno-test/-/shim-deno-test-0.3.3.tgz";
        sha512 = "Ge0Tnl7zZY0VvEfgsyLhjid8DzI1d0La0dgm+3m0/A8gZXgp5xwlyIyue5e4SCUuVB/3AH/0lun9LcJhhTwmbg==";
      };
    };
    "data-uri-to-buffer-4.0.0" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.0.tgz";
        sha512 = "Vr3mLBA8qWmcuschSLAOogKgQ/Jwxulv3RNE4FXnYWRGujzrRWQI4m12fQqRkwX06C0KanhLr4hK+GydchZsaA==";
      };
    };
    "fetch-blob-3.2.0" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz";
        sha512 = "7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.3.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.0.tgz";
        sha512 = "BKwRP/O0UvoMKp7GNdwPlObhYGB5DQqwhEDQlNKuoqwVYSxkSZCSbHjnFFmUEtwSKRPU4kNK8PbDYYitwaE3QA==";
      };
    };
    "web-streams-polyfill-3.2.1" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.2.1.tgz";
        sha512 = "e0MO3wdXWKrLbL0DgGnUV7WHVuw9OUvL4hjgnPkIeEvESk74gAITi5G606JtZPp39cd8HA9VQzCIvA49LpPN5Q==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
  };
in
{
  "@upstash/cli" = nodeEnv.buildNodePackage {
    name = "_at_upstash_slash_cli";
    packageName = "@upstash/cli";
    version = "0.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@upstash/cli/-/cli-0.2.0.tgz";
      sha512 = "EGZ3spI+XWFHlwMRW7NdhO/xG2kwswd7mhlOKQtoIgINo4L8n6UXHybBWhibiOfyl37YKH6PehKe2497cXUt/g==";
    };
    dependencies = [
      sources."@deno/shim-deno-0.5.0"
      sources."@deno/shim-deno-test-0.3.3"
      sources."data-uri-to-buffer-4.0.0"
      sources."fetch-blob-3.2.0"
      sources."formdata-polyfill-4.0.10"
      sources."isexe-2.0.0"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.3.0"
      sources."web-streams-polyfill-3.2.1"
      sources."which-2.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI for Upstash resources.";
      homepage = "https://github.com/upstash/cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
