version: "3"

includes:
  ci: ./scripts/Taskfile.ci.yml
  fmt: ./scripts/Taskfile.fmt.yml
  gen: ./scripts/Taskfile.gen.yml

tasks:
  isolate:
    desc: Drop into a isolated environment
    cmds:
      - ./scripts/isolate.sh

  build:all:
    desc: Build all derivations within `default.nix`
    cmds:
      - nix-build

  build:
    desc: Build a specific derivation
    deps:
      - clean
    cmds:
      - nix-build -A {{.CLI_ARGS}}

  clean:
    desc: remove all artifacts from `build`
    cmds:
      - rm -rf result*
      - rm -rf target
      - rm -rf tmp

  test:
    desc: Build and remove all build artifacts. Test whether all `nix` code is well-format and 'compilable'
    cmds:
      - task: build:all
      - task: clean

  fmt:
    desc: Run all formatting supported
    summary: |
      Runs all formatting supported.

      1. Runs fmt:md, which formats all Markdown using prettier
      2. Runs fmt:yaml, which formats all YAML using prettier
      3. Runs fmt:nix, which formats all Nix files with nixpkgs-fmt
    cmds:
      - task: fmt:default

  cfg:scripts:
    desc: Make scripts executable
    cmds:
      - chmod -R +x ./scripts
