repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shfmt
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        files: ^.*\.(yaml|yml|MD|md)$
  - repo: local
    hooks:
      - id: generate-npm-pkgs
        name: Generate Nodejs NIX Packages
        entry: pls build:node
        files: ^node/node-packages\.json$
        pass_filenames: false
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: pls fmt:nix
        files: ^.*\.nix$
        language: system
        pass_filenames: false

      - id: build-nix
        name: Build NIX Packages
        entry: pls test
        files: ^.*\.nix$
        language: system
        pass_filenames: false
