keywords: &keywords
  - BREAKING CHANGE
  - BREAKING CHANGES
  - BREAKING

presetConfig: &preset
  types:
    - type: fix
      section: Bug Fixes
    - type: new
      section: New Packages
    - type: update
      section: Updated Packages
    - type: docs
      section: Documentation Update
    - type: ci
      hidden: true
    - type: config
      hidden: true
    - type: chore
      hidden: true
    - type: release
      hidden: true

branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      parserOpts: *keywords
      releaseRules:
        - type: fix
          scope: drv
          release: patch
        - type: fix
          scope: config
          release: false
        - type: new
          release: minor
        - type: update
          release: major
        - type: docs
          scope: dev
          release: false
        - type: docs
          scope: pkg
          release: patch
        - type: ci
          release: false
        - scope: no-release
          release: false
        - type: release
          release: false
        - type: config
          release: false
      presetConfig: *preset
  - - "@semantic-release/release-notes-generator"
    - parserOpts: *keywords
      writerOpts:
        commitsSort:
          - subject
          - scope
      presetConfig: *preset
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - "message": "release: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
