name: "Cache on Cachix"
on:
  pull_request:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
    - name: Install Cachix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Cache builds
      uses: cachix/cachix-action@v10
      with:
        name: kirinnee-sample-binary-cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
