name: "Checks and Cache"
on:
  pull_request:
jobs:
  cache:
    runs-on: nix
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Cache builds
        uses: cachix/cachix-action@v10
        with:
          name: kirinnee-sample-binary-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        continue-on-error: true

      - name: Run Pre-commit checks
        run: nix-shell nix/shells.nix -A ci --run scripts/ci/pre-commit.sh
        env:
          NIXPKGS_ALLOW_UNFREE: "1"

      - name: Esnure builds
        run: nix-build
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
