name: "Checks and Cache"
on:
  pull_request:
jobs:
  cache:
    container: nixos/nix
    runs-on: ubuntu-20.04
    steps:
      - name: Install git and tar and bash
        run: apk add git tar bash

      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Install Cachix
        run: nix-env -i cachix

      - name: Cache builds
        uses: cachix/cachix-action@v10
        with:
          name: kirinnee-sample-binary-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Pre-commit checks
        run: nix-shell --run ./scripts/ci/pre-commit.sh

      - name: Esnure builds
        run: nix-build
