name: "Checks and Cache"
on:
  pull_request:
jobs:
  cache:
    container: nixos/nix
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Context
        run: echo 'hello'
