name: "Checks and Cache"
on:
  pull_request:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.1.0
        with:
          namespacelabs: false
      # pre commit
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh

      - name: Esnure builds
        run: nix-build
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
