name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v1.1.0
        with:
          namespacelabs: false

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
