name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    runs-on: nix
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v2.3.0
        with:
          binary_cache: kirinnee-sample-binary-cache

      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_PATH: nixpkgs=channel:nixos-unstable
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix-shell env/shells.nix -A releaser --run scripts/ci/release.sh
