name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    runs-on: nix
    steps:
      - name: AtomiCloud CI Environment
        uses: kirinnee/atomici-action@v2.3.1
        with:
          binary_cache: kirinnee-sample-binary-cache

      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
