name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_PATH: nixpkgs=channel:nixos-unstable
        run: nix-shell env/shells.nix -A releaser --run scripts/ci/release.sh
