name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    container: nixos/nix
    runs-on: ubuntu-20.04
    steps:
      - name: Install git and tar
        run: apk add git tar

      - name: Cache Whole of NIX
        uses: actions/cache@v2
        with:
          path: /nix
          key: ${{ runner.os }}-alpine-nix

      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Install Cachix
        run: |
          nix-env -i cachix
          cachix use kirinnee-sample-binary-cache

      - name: Install Environment
        run: nix-env -f ./env.nix -iA cd

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sg release
