name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: Release
    container: ghcr.io/kirinnee/nix-ci/nix-ci:main-152fe7
    runs-on: ubuntu-20.04
    steps:
      - name: Cache Whole of NIX
        uses: actions/cache@v2
        with:
          path: /nix
          key: ${{ runner.os }}-alpine-nix-release

      - name: Checkout Git
        uses: actions/checkout@v2.3.4

      - name: Install Cachix
        run: cachix use kirinnee-sample-binary-cache

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell env/shells.nix -A releaser --run scripts/ci/release.sh
